<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [2]:
# 참고사이트 : https://github.com/susanli2016/NLP-with-Python/blob/master/Fuzzy%20String%20Matching.ipynb

In [3]:
from random import *
import pandas as pd
import numpy as np
from pandas import DataFrame
%matplotlib inline
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

d:\pl\python\python37\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [4]:
# generate 100 dummy data
hash_tags = ['r', 'python', 'java', 'c', 'ruby']
tmp_dict = {
    'user_id':[],
    'hash_tags':[]
}

# 1 dummy has 1-5 tags
for i in range(100):
    n_tags = randint(1,5)
    random_tags = sample(hash_tags, n_tags)
    tmp_dict['user_id'].append(i)
    tmp_dict['hash_tags'].append(random_tags)

tmp_df = pd.DataFrame.from_dict(tmp_dict)
tmp_df.head(10)

   user_id                   hash_tags
0        0  [c, java, python, ruby, r]
1        1                    [python]
2        2              [python, java]
3        3                      [java]
4        4                      [c, r]
5        5                      [ruby]
6        6  [ruby, java, python, c, r]
7        7                         [r]
8        8                      [ruby]
9        9                   [r, ruby]

In [5]:
def sort_and_make_string(hash_tag_list):
    hash_tag_list.sort()
    return ' '.join(hash_tag_list)
    
    
def get_ratio(my_hash_tags, ur_hash_tags):
    # 나와 상대방의 해시태그를 알파벳 순으로 정렬한다.
    # 나와 상대방의 해시태그를 스트링으로 변환한다.
    my_hash_str = sort_and_make_string(my_hash_tags)
    ur_hash_str = sort_and_make_string(ur_hash_tags)
    # fuzzy match ratio 반환
    return fuzz.ratio(my_hash_str, ur_hash_str)

In [6]:
my_tag = ['r', 'python']
tmp_df['fuzzy_ratio'] = tmp_df['hash_tags'].apply(lambda ur_tag: get_ratio(my_tag, ur_tag))

In [14]:
# fuzzy_ratio 순으로 내림차순 정렬
tmp_df.sort_values(by=['fuzzy_ratio'], ascending=False)

    user_id                hash_tags  fuzzy_ratio
24       24              [python, r]          100
38       38              [python, r]          100
48       48              [python, r]          100
70       70           [c, python, r]           89
21       21                 [python]           86
65       65                 [python]           86
28       28                 [python]           86
1         1                 [python]           86
43       43                 [python]           86
78       78           [python, ruby]           84
10       10           [python, ruby]           84
32       32        [c, python, ruby]           76
22       22        [c, python, ruby]           76
35       35        [c, python, ruby]           76
19       19        [c, python, ruby]           76
54       54              [c, python]           75
20       20              [c, python]           75
34       34     [c, python, r, ruby]           70
86       86     [c, java, python, r]           70
62       62     [c, python, r, ruby]           70
23       23     [c, python, r, ruby]           70
72       72     [c, python, r, ruby]           70
12       12     [c, java, python, r]           70
92       92     [java, python, ruby]           67
18       18     [java, python, ruby]           67
2         2           [java, python]           63
49       49           [java, python]           63
57       57  [c, java, python, ruby]           62
87       87  [c, java, python, ruby]           62
14       14  [java, python, r, ruby]           62
..      ...                      ...          ...
56       56             [c, r, ruby]           25
66       66             [java, ruby]           24
37       37             [java, ruby]           24
36       36             [java, ruby]           24
27       27                      [r]           22
7         7                      [r]           22
63       63                      [r]           22
80       80                      [r]           22
81       81                      [r]           22
85       85          [c, java, ruby]           21
89       89          [java, r, ruby]           21
88       88          [c, java, ruby]           21
47       47          [java, r, ruby]           21
33       33          [java, r, ruby]           21
64       64          [c, java, ruby]           21
79       79          [java, r, ruby]           21
51       51       [c, java, r, ruby]           19
84       84                   [ruby]           17
60       60                   [ruby]           17
26       26                   [ruby]           17
25       25                   [ruby]           17
77       77                   [ruby]           17
8         8                   [ruby]           17
5         5                   [ruby]           17
83       83                   [java]            0
69       69                      [c]            0
61       61                   [java]            0
15       15                   [java]            0
42       42                      [c]            0
3         3                   [java]            0

[100 rows x 3 columns]

In [16]:
fuzz.ratio(['python', 'f'] , ['python', 's'])

93

In [ ]:
fuzz.ratio(['python', 'f'] , ['python', 's'])