<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
# 참고사이트 : https://github.com/susanli2016/NLP-with-Python/blob/master/Fuzzy%20String%20Matching.ipynb

In [2]:
from random import *
import pandas as pd
import numpy as np
from pandas import DataFrame
%matplotlib inline
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

d:\pl\python\python37\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [17]:
# generate 100 dummy data
hash_tags = ['r', 'python', 'java', 'c', 'ruby']
tmp_dict = {
    'user_id':[],
    'hash_tags':[]
}

# 1 dummy has 1-5 tags
for i in range(100):
    n_tags = randint(1,5)
    random_tags = sample(hash_tags, n_tags)
    tmp_dict['user_id'].append(i)
    tmp_dict['hash_tags'].append(random_tags)

tmp_df = pd.DataFrame.from_dict(tmp_dict)
tmp_df.head(10)

   user_id                   hash_tags
0        0                   [c, java]
1        1              [python, c, r]
2        2                         [r]
3        3                [java, ruby]
4        4  [java, c, python, ruby, r]
5        5              [java, python]
6        6                   [c, java]
7        7                      [ruby]
8        8        [r, java, c, python]
9        9  [ruby, java, python, c, r]

In [18]:
def sort_and_make_string(hash_tag_list):
    hash_tag_list.sort()
    return ' '.join(hash_tag_list)
    
    
def get_ratio(my_hash_tags, ur_hash_tags):
    # 나와 상대방의 해시태그를 알파벳 순으로 정렬한다.
    # 나와 상대방의 해시태그를 스트링으로 변환한다.
    my_hash_str = sort_and_make_string(my_hash_tags)
    ur_hash_str = sort_and_make_string(ur_hash_tags)
    # fuzzy match ratio 반환
    return fuzz.ratio(my_hash_str, ur_hash_str)

In [19]:
my_tag = ['r', 'python']
tmp_df['fuzzy_ratio'] = tmp_df['hash_tags'].apply(lambda ur_tag: get_ratio(my_tag, ur_tag))

In [20]:
# fuzzy_ratio 순으로 내림차순 정렬
tmp_df.sort_values(by=['fuzzy_ratio'], ascending=False)

    user_id             hash_tags  fuzzy_ratio
11       11        [c, python, r]           89
1         1        [c, python, r]           89
45       45        [c, python, r]           89
13       13              [python]           86
55       55              [python]           86
49       49              [python]           86
26       26              [python]           86
69       69        [python, ruby]           84
58       58        [python, ruby]           84
51       51        [python, ruby]           84
70       70        [python, ruby]           84
88       88     [c, python, ruby]           76
60       60           [c, python]           75
64       64           [c, python]           75
16       16           [c, python]           75
71       71  [c, java, python, r]           70
84       84  [c, java, python, r]           70
62       62  [c, java, python, r]           70
20       20  [c, python, r, ruby]           70
17       17  [c, python, r, ruby]           70
43       43  [c, java, python, r]           70
8         8  [c, java, python, r]           70
14       14  [c, java, python, r]           70
85       85  [c, java, python, r]           70
10       10  [c, java, python, r]           70
48       48  [c, java, python, r]           70
41       41  [c, python, r, ruby]           70
99       99        [java, python]           63
59       59        [java, python]           63
5         5        [java, python]           63
..      ...                   ...          ...
28       28          [c, r, ruby]           25
81       81          [c, r, ruby]           25
3         3          [java, ruby]           24
56       56          [java, ruby]           24
25       25          [java, ruby]           24
47       47          [java, ruby]           24
39       39                   [r]           22
74       74                   [r]           22
76       76                   [r]           22
91       91                   [r]           22
22       22                   [r]           22
2         2                   [r]           22
37       37       [c, java, ruby]           21
73       73       [c, java, ruby]           21
27       27       [c, java, ruby]           21
12       12    [c, java, r, ruby]           19
82       82    [c, java, r, ruby]           19
40       40    [c, java, r, ruby]           19
89       89                [ruby]           17
30       30                [ruby]           17
7         7                [ruby]           17
54       54                [ruby]           17
86       86             [c, java]           14
24       24             [c, java]           14
31       31             [c, java]           14
32       32             [c, java]           14
6         6             [c, java]           14
0         0             [c, java]           14
87       87                [java]            0
93       93                [java]            0

[100 rows x 3 columns]